export { default as Default } from './Default';
export { default as TwoPane } from './TwoPane';
export { default as Classic } from './Classic';
export { default as FourByFour } from './FourByFour';
export { default as OnePane } from './OnePane';
export { default as Triplets } from './Triplets';
export { default as OnePaneR } from './OnePaneR';
export { default as Pyramid } from './Pyramid';
export { default as Preferred } from './Preferred';
