import { ISourceDisplayData } from './index';
import { $t } from 'services/i18n';

const imageSupport = ['png', 'jpg', 'jpeg', 'gif', 'tga', 'bmp'];
const mediaSupport = [
  'mp4',
  'ts',
  'mov',
  'flv',
  'mkv',
  'avi',
  'mp3',
  'ogg',
  'aac',
  'wav',
  'gif',
  'webm',
];
const colorSupport = ['Hex', 'RGBA', 'HSV'];

export const SourceDisplayData = (): { [key: string]: ISourceDisplayData } => ({
  image_source: {
    name: $t('Image'),
    description: $t('Add images to your scene.'),
    shortDesc: $t('Add image to scene'),
    demoFilename: 'image.png',
    supportList: imageSupport,
    icon: 'icon-image',
    group: 'media',
  },
  color_source: {
    name: $t('Color Block'),
    shortDesc: $t('Add color to scene'),
    description: $t('Add a color to the background of your whole scene or just a part.'),
    demoFilename: 'color-source.png',
    supportList: colorSupport,
    icon: 'fas fa-fill',
    group: 'media',
  },
  browser_source: {
    name: $t('Browser Source'),
    description: $t(
      'Allows you to add web-based content as a source, such as web pages, widgets, and streaming video.',
    ),
    shortDesc: $t('Your web-based content'),
    demoFilename: 'browser-source.png',
    supportList: [$t('Websites'), $t('Third party widgets'), 'HTML'],
    icon: 'fas fa-globe',
    group: 'capture',
  },
  ffmpeg_source: {
    name: $t('Media File'),
    description: $t('Add videos or sound clips to your scene.'),
    shortDesc: $t('Videos or sound clips'),
    demoFilename: 'media.png',
    supportList: mediaSupport,
    icon: 'far fa-file-video',
    group: 'media',
  },
  slideshow: {
    name: $t('Image Slide Show'),
    description: $t('Add a slideshow of images to your scene.'),
    shortDesc: $t('Add a slideshow'),
    demoFilename: 'image-slide-show.png',
    supportList: imageSupport,
    icon: 'icon-image',
    group: 'media',
  },
  text_gdiplus: {
    name: $t('Text (GDI+)'),
    shortDesc: $t('Add text to scene'),
    description: $t('Add text to your scene and adjust its style.'),
    demoFilename: 'text.png',
    supportList: [...colorSupport, $t('System Fonts'), $t('System Sizes')],
    icon: 'fas fa-font',
    group: 'media',
  },
  monitor_capture: {
    name: $t('Display Capture'),
    shortDesc: $t('Share monitor'),
    description: $t('Capture your entire computer monitor.'),
    demoFilename: 'display-capture.png',
    supportList: [$t('Primary monitor'), $t('Secondary monitor')],
    icon: 'fas fa-desktop',
    group: 'capture',
  },
  window_capture: {
    name: $t('Window Capture'),
    shortDesc: $t('Share specific window'),
    description: $t("Capture a specific window that's open on your computer."),
    demoFilename: 'window-capture.png',
    supportList: [$t('Compatible with most modern browsers and programs')],
    icon: 'icon-editor-9',
    group: 'capture',
  },
  game_capture: {
    name: $t('Game Capture'),
    description: $t("Capture a game you're playing on your computer."),
    shortDesc: $t('Capture your game'),
    demoFilename: 'game-capture.png',
    supportList: [$t('Built in works with most modern computer games')],
    icon: 'fas fa-gamepad',
    group: 'capture',
  },
  dshow_input: {
    name: $t('Video Capture'),
    shortDesc: $t('Camera / Capture Card'),
    description: $t('Display video from webcams, capture cards, and other devices.'),
    demoFilename: 'video-capture.png',
    supportList: [
      $t('Built in webcam'),
      $t('Logitech webcam'),
      $t('Capture cards (Elgato, Avermedia, BlackMagic)'),
    ],
    icon: 'icon-webcam',
    group: 'av',
  },
  ndi_source: {
    name: $t('NDI source'),
    shortDesc: $t('Capture NDI output'),
    description: $t('Allow you to capture NDI output streams.'),
    icon: 'fas fa-file',
    group: 'capture',
  },
  'decklink-input': {
    name: $t('Blackmagic Device'),
    description: $t('Capture the feed your decklink device is capturing.'),
    demoFilename: 'sources.png',
    supportList: [$t('Works with most of the recent Blackmagic cards.')],
    icon: 'fas fa-file',
  },
  openvr_capture: {
    name: $t('OpenVR Capture'),
    description: $t('Directly capture the OpenVR monitoring video buffer of your HMD.'),
    shortDesc: $t('Capture VR games'),
    demoFilename: 'vr-capture.png',
    supportList: ['OpenVR', 'SteamVR'],
    icon: 'fab fa-simplybuilt fa-rotate-180',
    group: 'capture',
  },
  screen_capture: {
    name: $t('Screen Capture'),
    description: $t('Capture your game, other applications, or your entire monitor'),
    shortDesc: $t('Capture screen'),
    demoFilename: 'window-capture.png',
    supportList: [$t('Most games, apps, displays')],
    icon: 'icon-group',
    group: 'capture',
  },
  mac_screen_capture: {
    name: $t('macOS Screen Capture'),
    shortDesc: $t('Capture screen'),
    description: $t('Capture your game, other applications, or your entire monitor'),
    demoFilename: 'window-capture.png',
    supportList: [$t('Most games, apps, displays')],
    icon: 'icon-group',
    group: 'capture',
  },
  liv_capture: {
    name: $t('LIV Client Capture'),
    description: $t(
      'Directly capture the LIV compositor output, reducing load and simplifying setup for Mixed Reality.',
    ),
    demoFilename: 'vr-capture.png',
    supportList: ['LIV'],
    icon: 'fab fa-simplybuilt fa-rotate-180',
    group: 'capture',
  },
  wasapi_input_capture: {
    name: $t('Audio Input Capture'),
    description: $t(
      'Any device that attaches to a computer for the purpose of capturing sound, such as music or speech.',
    ),
    shortDesc: $t('Capture microphone'),
    demoFilename: 'audio-input.png',
    supportList: [$t('Built in microphones'), $t('USB microphones'), $t('Other USB devices')],
    icon: 'icon-mic',
    group: 'av',
  },
  wasapi_output_capture: {
    name: $t('Audio Output Capture'),
    shortDesc: $t('Capture desktop audio'),
    description: $t(
      'Captures your desktop audio for the purpose of playing sound, such as music or speech.',
    ),
    demoFilename: 'audio-output.png',
    supportList: [$t('Desktop audio')],
    icon: 'icon-audio',
    group: 'av',
  },
  scene: {
    name: $t('Scene'),
    shortDesc: $t('Existing scene'),
    description: $t('Allows you to add existing scene as a source'),
    demoFilename: 'scene.png',
    icon: 'far fa-object-group',
    group: 'media',
  },
  text_ft2_source: {
    name: $t('Text (FreeType 2)'),
    description: $t('Add text to your scene and adjust its style.'),
    demoFilename: 'text.png',
    supportList: [...colorSupport, $t('System Fonts'), $t('System Sizes')],
    icon: 'fas fa-font',
    group: 'media',
  },
  ovrstream_dc_source: {
    name: 'OvrStream',
    description: '',
    icon: 'fas fa-file',
    group: 'capture',
  },
  vlc_source: {
    name: $t('VLC Source'),
    shortDesc: $t('Video playlist'),
    description: $t('Add playlists of videos to your scene.'),
    icon: 'fas fa-play',
    group: 'media',
  },
  coreaudio_input_capture: {
    name: $t('Audio Input Capture'),
    shortDesc: $t('Capture microphone'),
    description: $t(
      'Any device that attaches to a computer for the purpose of capturing sound, such as music or speech.',
    ),
    demoFilename: 'audio-input.png',
    supportList: [$t('Built in microphones'), $t('USB microphones'), $t('Other USB devices')],
    icon: 'icon-mic',
    group: 'av',
  },
  coreaudio_output_capture: {
    name: $t('Audio Output Capture'),
    shortDesc: $t('Capture desktop audio'),
    description: $t(
      'Captures your desktop audio for the purpose of playing sound, such as music or speech.',
    ),
    demoFilename: 'audio-output.png',
    supportList: [$t('Desktop audio')],
    icon: 'icon-audio',
    group: 'av',
  },
  av_capture_input: {
    name: $t('Video Capture'),
    shortDesc: $t('Camera / Capture Card'),
    description: $t('Display video from webcams, capture cards, and other devices.'),
    demoFilename: 'video-capture.png',
    supportList: [
      $t('Built in webcam'),
      $t('Logitech webcam'),
      $t('Capture cards (Elgato, Avermedia, BlackMagic)'),
    ],
    icon: 'icon-webcam',
    group: 'av',
  },
  display_capture: {
    name: $t('Display Capture'),
    shortDesc: $t('Share monitor'),
    description: $t('Capture your entire computer monitor.'),
    demoFilename: 'display-capture.png',
    supportList: [$t('Primary monitor'), $t('Secondary monitor')],
    icon: 'fas fa-desktop',
    group: 'capture',
  },
  'syphon-input': {
    name: $t('Game Capture'),
    shortDesc: $t('Capture your game'),
    description: $t("Capture a game you're playing on your computer."),
    demoFilename: 'game-capture.png',
    supportList: [$t('Built in works with most modern computer games')],
    icon: 'fas fa-gamepad',
    group: 'capture',
  },
  audio_line: {
    name: $t('JACK Input Client'),
    description: $t(''),
    icon: 'fas fa-file',
    group: 'av',
  },
  soundtrack_source: {
    name: $t('Twitch Soundtrack'),
    description: $t(
      'Audio source working with the Twitch Soundtrack music application. Add this source to be able to filter out the music from your Twitch VODs.',
    ),
    icon: 'fas fa-file',
  },
  replay: {
    name: $t('Instant Replay'),
    shortDesc: $t('Display latest replay'),
    description: $t('Automatically plays your most recently captured replay in your stream.'),
    demoFilename: 'media.png',
    icon: 'icon-replay-buffer',
    group: 'media',
  },
  icon_library: {
    name: $t('Custom Icon'),
    description: $t('Displays an icon from one of many selections'),
    demoFilename: 'image.png',
    icon: 'fas fa-file',
  },
  streamlabel: {
    name: $t('Stream Label'),
    description: $t(
      'Include text into your stream, such as follower count, latest tip, last sub and more.',
    ),
    demoFilename: 'source-stream-labels.png',
    supportList: [
      $t('New Followers'),
      $t('New Subscribers'),
      $t('New Cheers'),
      $t('New Tips'),
      $t('All-Time Top Tipper'),
      $t('Weekly Top Tipper'),
      $t('Monthly Follows'),
      $t('And more'),
    ],
    icon: 'fas fa-file',
    shortDesc: $t('Stream stats and events'),
  },
  mediasoupconnector: {
    name: $t('Collab Cam'),
    shortDesc: $t('Stream with guests'),
    description: $t(
      'Invite guests to join your stream from a web browser or their Streamlabs Desktop. Stream games or IRL broadcasts together, use as additional camera angles and more.',
    ),
    demoFilename: 'source-collab-cam.png',
    icon: 'icon-team-2',
    group: 'av',
  },
  wasapi_process_output_capture: {
    name: $t('Application Audio'),
    shortDesc: $t('Beta'),
    description: $t('Capture the audio coming from a specific application.'),
    icon: 'fas fa-user',
    group: 'av',
  },
  spout_capture: {
    name: $t('Spout2 capture'),
    shortDesc: $t('Vtube support'),
    description: $t(
      'Virtual avatar capture source. Enables high resolution, zero-compression and zero-latency video capture from VTube third-party software.',
    ),
    demoFilename: 'source-spout2-thumbnail.gif',
    supportList: ['VSeeFace', 'VTube Studio'],
    icon: 'icon-face-masks-3',
    link: 'https://streamlabs.com/content-hub/post/vtuber-support-on-streamlabs-desktop',
    linkText: $t('Learn how to set it up'),
    group: 'capture',
  },
});
